### ISSUE TITLE
Our commitments to improve

### ISSUE THREAD

**Issue by nutshoekey** [adriel723/ICT2201-Team-Project#17]

**Comment by adrian98ng** [comment]
Reduce the number of meetings; meetings should not be held to do work
Should pay more attention to details

**Comment by adriel723** [comment]
Assign tasks and fix a deadline, check in more often of progress with team members

**Comment by shathicurri01** [comment]
I should take more initiative to update others on the current tasks we are working on.
I should take more initiative to check up on if others need assistance in their part of the work, once i am done with mine

**Comment by nutshoekey** [comment]
Haiqi:
1. Have the initiative to take ownership of tasks
2. Inform the team member you are collaborating with on the task
3. Keep meetings short, meet only when the task is done and discuss how to move forward
