### ISSUE TITLE
What went well

### ISSUE THREAD

**Issue by nutshoekey** [adriel723/ICT2201-Team-Project#20]

**Comment by shathicurri01** [comment]
We managed to finish it before the deadline and had enough time to do some final touches

**Comment by adrian98ng** [comment]
All the work was completed on time
Everybody was present in group meetings and the group have no communication problems

**Comment by nutshoekey** [comment]
Haiqi:
Milestone was completed on time

**Comment by adriel723** [comment]
We managed to finish our individual tasks and submit Milestone 1 on time with no issues
