### ISSUE TITLE
What could be improved?

### ISSUE THREAD

**Issue by nutshoekey** [adriel723/ICT2201-Team-Project#21]

**Comment by adriel723** [comment]
Adriel: Team leader could be more dominant and firm

**Comment by shathicurri01** [comment]
Gantt Chart : should have included the workload distribution
Team management : Could have updated each other on their updates every week

**Comment by nutshoekey** [comment]
Haiqi: 
1. Ownership of tasks was not followed closely (collaboration without updating the assignees)
2. Team Dynamics - we did not meet after finishing tasks, instead we met to do tasks (unnecessary meetings)

**Comment by adrian98ng** [comment]
Use case diagram should be more accurate
Use case transactions have some minor mistakes that can be avoided
