### ISSUE TITLE
M1 Review: Project Management

### ISSUE THREAD

**Issue by adriel723** [adriel723/ICT2201-Team-Project#26]
Gantt Chart:
Put names for every task in Gantt Chart 
Assign tasks accordingly based on team member's roles

WBS Diagram:
Should not have more than 6 subtasks

**Comment by adriel723** [comment]
I will update the Gantt Chart and WBS and put it inside M2 report

**Comment by nutshoekey** [comment]
Have you updated the gantt chart and wbs?

**Comment by adriel723** [comment]
Yes, have updated both the Gantt Chart and WBS.
