### ISSUE TITLE
M1 Review: Use Case Descriptions

### ISSUE THREAD

**Issue by adriel723** [adriel723/ICT2201-Team-Project#27]
UCD 1: Define alternative scenario more clearly.
UCD 2: Change confirmation message to confirmation prompt.
UCD 5: Include staff's abort use case scenario; include an alternative scenario to abort operation
UCD 6: Alternative Scenario 4a1: Include system error as a reason why notification not sent

**Comment by adriel723** [comment]
Have updated all use cases and added new use cases, will put them in the appendix A of the M2 report

**Comment by nutshoekey** [comment]
Reviewed the UCDs, looks correct, will close the issue
