### ISSUE TITLE
M2: Class Diagram

### ISSUE THREAD

**Issue by adriel723** [adriel723/ICT2201-Team-Project#29]

**Comment by adriel723** [comment]
Have started on the class diagram together with Haiqi

**Comment by nutshoekey** [comment]
Should be able to finish in 2 days, then we can start on Component Diagram

**Comment by nutshoekey** [comment]
Class diagram has been finalised with @adriel723, we can now move onto component diagram

**Comment by nutshoekey** [comment]
@adriel723 please check that this is the finalised class diagram to use in M2 report

![Image](https://user-images.githubusercontent.com/44663281/197510524-24878d25-cb38-4fe3-acc8-31fd7fa024de.png)

**Comment by adriel723** [comment]
Looks good to me, will add this to the M2 report.
