### ISSUE TITLE
What could be improved?

### ISSUE THREAD

**Issue by nutshoekey** [adriel723/ICT2201-Team-Project#31]
Haiqi:

Ownership of tasks was mostly followed, except in cases where review from fresh eyes was needed
Team Dynamics - Better than M1, however could still be better
Could have more meetings this round

Adrian:
Meetings were more frequent and productive but overshots the original time given for the meeting.
GitHub has to be updated often. Frequency has to be consistent.

Shathiya:
We could have updated the github more often.
Communication within the group was good, but can be further improved by providing more updates.

Adriel: GitHub can be updated more often. Meetings and updates can be more frequent

**Comment by nutshoekey** [comment]
Haiqi:

Ownership of tasks was mostly followed, except in cases where review from fresh eyes was needed
Team Dynamics - Better than M1, however could still be better
Could have more meetings this round

**Comment by adrian98ng** [comment]
Adrian:
Meetings were more frequent and productive but overshots the original time given for the meeting. 
GitHub has to be updated often. Frequency has to be consistent.

**Comment by shathicurri01** [comment]
Shathiya:
We could have updated the github more often.
Communication within the group was good, but can be further improved by providing more updates.

**Comment by adriel723** [comment]
Adriel: GitHub can be updated more often. Meetings and updates can be more frequent
