### ISSUE TITLE
What went well

### ISSUE THREAD

**Issue by nutshoekey** [adriel723/ICT2201-Team-Project#32]
Haiqi:
Milestone was completed on time

Shathiya:
M2 was completed smoothly and was able to submit promptly

Adrian:
Work was distributed evenly and completed on time.

Adriel: No delays in submission.

**Comment by nutshoekey** [comment]
Haiqi:
Milestone was completed on time

**Comment by shathicurri01** [comment]
Shathiya:
M2 was completed smoothly and was able to submit promptly

**Comment by adrian98ng** [comment]
Adrian: 
Work was distributed evenly and completed on time.

**Comment by adriel723** [comment]
Adriel: No delays in submission.
