### ISSUE TITLE
Our commitments to improve

### ISSUE THREAD

**Issue by nutshoekey** [adriel723/ICT2201-Team-Project#33]
Haiqi:

Inform the team member you are collaborating with on the task
Schedule meetings in advance

Adrian:
Include reminders to update GitHub project board.

Shathiya:
Can ask if the other team members need help after finishing our own tasks
Can check up on each other if their work seems to be incomplete or if they are not on time with their updates

Adriel: Check up on other group members more often, set deadlines and enquire if any issues to meet them in advance.

**Comment by nutshoekey** [comment]
Haiqi:

Inform the team member you are collaborating with on the task
Schedule meetings in advance

**Comment by adrian98ng** [comment]
Adrian:
Include reminders to update GitHub project board.

**Comment by shathicurri01** [comment]
Shathiya:
Can ask if the other team members need help after finishing our own tasks
Can check up on each other if their work seems to be incomplete or if they are not on time with their updates

**Comment by adriel723** [comment]
Adriel: Check up on other group members more often, set deadlines and enquire if any issues to meet them in advance.
