### ISSUE TITLE
M2 Review

### ISSUE THREAD

**Issue by adrian98ng** [adriel723/ICT2201-Team-Project#34]
Main point to focus :
Class diagram, sequence , component, architecture pattern

Component diagram
If there is interface, some other component must interact with it
All product need a interface (clarify with prof alex)
Need to edit labelling for M3

Sequence diagram
Object id : namespace
Lifeline should have a connection, should not be empty
Connection to DB need to have a brief sql statement, return should be a array or value

Class diagram
Direction for arrow should be control to entity

Architecture diagram
Client server model

Anything with the word management is a server (requires logic to work on)
Github

Need to be more frequent with our updates
Numbering of task according to gantt chart
M1 retrospect = leader or someone can do a summary of everyone’s input

**Comment by shathicurri01** [comment]
Meeting Minutes updated

**Comment by nutshoekey** [comment]
Will update according to the minutes
