### ISSUE TITLE
3.5.1 Review Black Box Testing

### ISSUE THREAD

**Issue by adrian98ng** [adriel723/ICT2201-Team-Project#37]

**Comment by adrian98ng** [comment]
Around 20% completed. Continue to liaise with Adriel to ensure that the prototype and the black box testing are consistent.

**Comment by adriel723** [comment]
Hi Adrian, hows the progress going for black box?

**Comment by adrian98ng** [comment]
Hey Adriel,
Currently still working on the decision tables, halfway done now, will complete within the next 48 hours

**Comment by adrian98ng** [comment]
Completed all the different scenarios for black box testing

**Comment by adrian98ng** [comment]
Hi, Adriel, you may close this issue once you are done reviewing our work, thanks!

**Comment by adriel723** [comment]
Have reviewed it, looks good. Will be closing this issue. Thank you both for your hard work!
